[package]
name = "smt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
glob = "0.3.1"
log = "0.4.22"
pretty_env_logger = "0.5.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
